CREATE TABLE IF NOT EXISTS record_entity (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS waste_bucket (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    bucket_no VARCHAR(50) NOT NULL UNIQUE,
    category VARCHAR(30) NOT NULL,
    weight DECIMAL(10, 2) NOT NULL,
    has_special_ingredients BOOLEAN NOT NULL,
    special_ingredients_remark VARCHAR(500),
    experiment_name VARCHAR(200) NOT NULL,
    experiment_time DATETIME NOT NULL,
    lab_room VARCHAR(50) NOT NULL,
    student_id VARCHAR(50) NOT NULL,
    student_name VARCHAR(50) NOT NULL,
    student_contact VARCHAR(200),
    qr_code VARCHAR(200) UNIQUE,
    status VARCHAR(30) NOT NULL,
    submitted_at DATETIME,
    safety_officer_id VARCHAR(50),
    safety_officer_name VARCHAR(50),
    safety_checked_at DATETIME,
    safety_remark VARCHAR(500),
    storage_operator_id VARCHAR(50),
    storage_operator_name VARCHAR(50),
    stored_at DATETIME,
    recycler_id VARCHAR(50),
    recycler_name VARCHAR(50),
    collected_at DATETIME,
    category_correction_remark VARCHAR(1000),
    created_at DATETIME,
    updated_at DATETIME,
    INDEX idx_status (status),
    INDEX idx_category (category),
    INDEX idx_student_id (student_id),
    INDEX idx_lab_room (lab_room),
    INDEX idx_qr_code (qr_code)
);
